name: ğŸ”— GHA
on:
  # push:
    # tags:
    #   - v0.**

    # branches: [ github-workflows ]

  workflow_dispatch:


jobs:
  # android-build:
  #   name: ğŸ¤– Android
  #   uses: ./.github/workflows/android.yml

  # ios-build:
  #   name: ğŸ iOS
  #   uses: ./.github/workflows/ios.yml

  linux-build:
    name: ğŸ§ Linux
    uses: ./.github/workflows/linux.yml

  # macos-build:
  #   name: ğŸ macOS
  #   uses: ./.github/workflows/macos.yml

  # windows-build:
  #   name: ğŸ Windows
  #   uses: ./.github/workflows/windows.yml

  # web-build:
  #   name: ğŸŒ Web
  #   uses: ./.github/workflows/web.yml
