name: ğŸ”— GHA
on:
  workflow_dispatch:
    inputs:
      godot_treeish:
        description: A tag, branch or commit hash in the Godot repository.
        type: string
        default: master
      limboai_treeish:
        description: A tag, branch or commit hash in the LimboAI repository.
        type: string
        default: master

jobs:
  # android-build:
  #   name: ğŸ¤– Android
  #   uses: ./.github/workflows/android.yml

  # ios-build:
  #   name: ğŸ iOS
  #   uses: ./.github/workflows/ios.yml

  linux-build:
    name: ğŸ§ Linux
    uses: ./.github/workflows/linux.yml
    with:
      godot_treeish: ${{ inputs.godot_treeish }}
      limboai_treeish: ${{ inputs.limboai_treeish }}

  macos-build:
    name: ğŸ macOS
    uses: ./.github/workflows/macos.yml
    with:
      godot_treeish: ${{ inputs.godot_treeish }}
      limboai_treeish: ${{ inputs.limboai_treeish }}

  windows-build:
    name: ğŸªŸ Windows
    uses: ./.github/workflows/windows.yml
    with:
      godot_treeish: ${{ inputs.godot_treeish }}
      limboai_treeish: ${{ inputs.limboai_treeish }}

  # web-build:
  #   name: ğŸŒ Web
  #   uses: ./.github/workflows/web.yml
